//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Connection
{
    using System;
    using System.Collections.Generic;
    
    public partial class AllGoods
    {
        public int GoodsID { get; set; }
        public string GoodsName { get; set; }
        public string GoodsDefineDate { get; set; }
        public int ArzID { get; set; }
        public decimal BuyPrice { get; set; }
    
        public virtual Arz Arz { get; set; }
    }
}
