//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Connection
{
    using System;
    using System.Collections.Generic;
    
    public partial class Arz
    {
        public Arz()
        {
            this.AllGoods = new HashSet<AllGoods>();
        }
    
        public int ArzID { get; set; }
        public string ArzName { get; set; }
        public decimal ArzPrice { get; set; }
    
        public virtual ICollection<AllGoods> AllGoods { get; set; }
    }
}
